# Generated by Django 5.1.2 on 2024-11-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ram', max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=8)),
                ('martial', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='Married', max_length=20)),
                ('age', models.PositiveIntegerField(default=30)),
                ('salary', models.FloatField(blank=True, default=0.0)),
                ('family_income', models.FloatField(blank=True, default=0.0)),
                ('home_value', models.FloatField(blank=True, default=0.0)),
                ('loan_amount', models.PositiveIntegerField(default=0.0)),
                ('tenure', models.PositiveIntegerField(choices=[(10, 10), (15, 15)], default=15)),
                ('interest', models.FloatField(default=9.41)),
            ],
        ),
    ]
