# Generated by Django 5.1.2 on 2024-12-01 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='loan_amount',
            field=models.PositiveIntegerField(default=0.0, validators=[django.core.validators.MaxValueValidator(400000), django.core.validators.MinValueValidator(15000000)]),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='name',
            field=models.CharField(default='Ram Rai', max_length=100),
        ),
    ]
