# Generated by Django 5.1.2 on 2024-12-01 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_alter_clientdetails_loan_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='loan_amount',
            field=models.PositiveIntegerField(default=400000, validators=[django.core.validators.MinValueValidator(400000), django.core.validators.MaxValueValidator(15000000)]),
        ),
    ]
