# Generated by Django 5.1.2 on 2024-12-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0003_alter_clientdetails_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='home_value',
            field=models.FloatField(blank=True, default=571430),
        ),
    ]
